// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "email": "support@upworkjobapi.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api-keys/refresh-cache": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Forces a refresh of the API keys cache from Firestore",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "api-keys"
                ],
                "summary": "Refresh API keys cache",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.JobsResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/server.JobsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.JobsResponse"
                        }
                    }
                }
            }
        },
        "/api-keys/{key}/cache": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Removes a specific API key from the cache",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "api-keys"
                ],
                "summary": "Clear API key cache",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API key to clear from cache",
                        "name": "key",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.JobsResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/server.JobsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.JobsResponse"
                        }
                    }
                }
            }
        },
        "/cache/clear": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Removes all cached responses (does not affect API key cache)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cache"
                ],
                "summary": "Clear all response caches",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.JobsResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/server.JobsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.JobsResponse"
                        }
                    }
                }
            }
        },
        "/cache/stats": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns cache hit/miss ratio and performance metrics",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cache"
                ],
                "summary": "Get cache statistics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/server.JobsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.JobsResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns a 200 response when the API is up.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.JobsResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/server.JobsResponse"
                        }
                    }
                }
            }
        },
        "/jobs": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve normalized job documents with optional filters.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "List jobs",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Number of records (1-50)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filter by payment verification",
                        "name": "payment_verified",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by category slug",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by category group slug",
                        "name": "category_group",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by job status (open|closed or numeric code)",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by job type (hourly|fixed-price or numeric code)",
                        "name": "job_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by contractor tier (entry|intermediate|expert or numeric code)",
                        "name": "contractor_tier",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by buyer country",
                        "name": "country",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated required tags",
                        "name": "tags",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "ISO timestamp lower bound",
                        "name": "posted_after",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "ISO timestamp upper bound",
                        "name": "posted_before",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Minimum fixed budget",
                        "name": "budget_min",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Maximum fixed budget",
                        "name": "budget_max",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort mode (posted_on_asc, posted_on_desc, last_visited_asc, last_visited_desc)",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.JobsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.JobsResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/server.JobsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.JobsResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "server.BudgetInfo": {
            "type": "object",
            "properties": {
                "currency": {
                    "type": "string"
                },
                "fixed_amount": {
                    "type": "number"
                }
            }
        },
        "server.BuyerDTO": {
            "type": "object",
            "properties": {
                "active_assignments": {
                    "type": "integer"
                },
                "city": {
                    "type": "string"
                },
                "company_industry": {
                    "type": "string"
                },
                "company_size": {
                    "type": "integer"
                },
                "contract_date": {
                    "type": "string"
                },
                "country": {
                    "type": "string"
                },
                "feedback_count": {
                    "type": "integer"
                },
                "open_jobs_count": {
                    "type": "integer"
                },
                "payment_verified": {
                    "type": "boolean"
                },
                "score": {
                    "type": "number"
                },
                "timezone": {
                    "type": "string"
                },
                "total_assignments": {
                    "type": "integer"
                },
                "total_hours": {
                    "type": "number"
                },
                "total_jobs_with_hires": {
                    "type": "integer"
                },
                "total_spent": {
                    "type": "number"
                }
            }
        },
        "server.CategoryInfo": {
            "type": "object",
            "properties": {
                "group": {
                    "type": "string"
                },
                "group_slug": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                }
            }
        },
        "server.ClientActivity": {
            "type": "object",
            "properties": {
                "invitations_sent": {
                    "type": "integer"
                },
                "last_buyer_activity": {
                    "type": "string"
                },
                "total_applicants": {
                    "type": "integer"
                },
                "total_hired": {
                    "type": "integer"
                },
                "total_invited_to_interview": {
                    "type": "integer"
                },
                "unanswered_invites": {
                    "type": "integer"
                }
            }
        },
        "server.HourlyBudget": {
            "type": "object",
            "properties": {
                "currency": {
                    "type": "string"
                },
                "max": {
                    "type": "number"
                },
                "min": {
                    "type": "number"
                }
            }
        },
        "server.JobDTO": {
            "type": "object",
            "properties": {
                "budget": {
                    "$ref": "#/definitions/server.BudgetInfo"
                },
                "buyer": {
                    "$ref": "#/definitions/server.BuyerDTO"
                },
                "category": {
                    "$ref": "#/definitions/server.CategoryInfo"
                },
                "ciphertext": {
                    "type": "string"
                },
                "client_activity": {
                    "$ref": "#/definitions/server.ClientActivity"
                },
                "contractor_tier": {
                    "type": "string"
                },
                "created_on": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "duration_label": {
                    "type": "string"
                },
                "engagement": {
                    "type": "string"
                },
                "hide_budget": {
                    "type": "boolean"
                },
                "hourly_budget": {
                    "$ref": "#/definitions/server.HourlyBudget"
                },
                "id": {
                    "type": "string"
                },
                "is_contract_to_hire": {
                    "type": "boolean"
                },
                "is_private": {
                    "type": "boolean"
                },
                "job_type": {
                    "type": "string"
                },
                "last_visited_at": {
                    "type": "string"
                },
                "location": {
                    "$ref": "#/definitions/server.JobLocation"
                },
                "number_of_positions": {
                    "type": "integer"
                },
                "occupations": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "posted_on": {
                    "type": "string"
                },
                "premium": {
                    "type": "boolean"
                },
                "privacy_reason": {
                    "type": "string"
                },
                "proposals_tier": {
                    "type": "string"
                },
                "publish_time": {
                    "type": "string"
                },
                "publish_time_relative": {
                    "type": "string"
                },
                "qualifications": {
                    "$ref": "#/definitions/server.JobQualifications"
                },
                "recno": {
                    "type": "integer"
                },
                "skills": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "status": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "tier_text": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "was_renewed": {
                    "type": "boolean"
                },
                "weekly_retainer_budget": {
                    "$ref": "#/definitions/server.BudgetInfo"
                },
                "workload": {
                    "type": "string"
                }
            }
        },
        "server.JobLocation": {
            "type": "object",
            "properties": {
                "city": {
                    "type": "string"
                },
                "country": {
                    "type": "string"
                },
                "timezone": {
                    "type": "string"
                }
            }
        },
        "server.JobQualifications": {
            "type": "object",
            "properties": {
                "min_hours_week": {
                    "type": "number"
                },
                "min_job_success_score": {
                    "type": "integer"
                },
                "min_odesk_hours": {
                    "type": "integer"
                },
                "pref_english_skill": {
                    "type": "integer"
                },
                "rising_talent": {
                    "type": "boolean"
                },
                "should_have_portfolio": {
                    "type": "boolean"
                }
            }
        },
        "server.JobsResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/server.JobDTO"
                    }
                },
                "last_updated": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "X-API-KEY",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "",
	Schemes:          []string{"http", "https"},
	Title:            "Upwork Job API",
	Description:      "API for accessing normalized Upwork job listings with advanced filtering capabilities. All endpoints require authentication via X-API-KEY header.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
